steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: [ 'clean', 'install' ]
    env:
      -  'LOCAL_SOURCE_DIR=.'
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-east1-docker.pkg.dev/algus-project-382/algus-docker-repo/el-service:0.1', '.' ]
images:
  - 'us-east1-docker.pkg.dev/algus-project-382/algus-docker-repo/el-service:0.1'