version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - EL_DATA_PG:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5432:5432
volumes:
  EL_DATA_PG: