storage:
  source:
    directory: ${LOCAL_SOURCE_DIR}/
    extension: ${FILE_EXT:.pdf}

quarkus:
  log:
    category:
      "org.example":
        level: INFO

"%dev":
  quarkus:
    http:
      port: 8181
    log:
      category:
        "org.example":
          level: DEBUG

"%test":
  quarkus:
    http:
      test-port: 8888
  testing:
    relative-dir: pdf/