storage:
  source:
    directory: ${LOCAL_SOURCE_DIR:${USERPROFILE:${HOME}}/esl}/
    extension: ${FILE_EXT:.pdf}
  type: ${STORAGE_TYPE:LOCAL}
  gs:
    project: ${GCP_PPROJECT:algus-project-382}
    bucket: ${GCP_EL_BUCKET:algus-bucket}

quarkus:
  log:
    category:
      "org.example":
        level: DEBUG
  package:
    type: uber-jar
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql:postgres
      max-size: 8

"%dev":
  quarkus:
    http:
      port: 8181
    log:
      category:
        "org.example":
          level: DEBUG

"%test":
  quarkus:
    http:
      test-port: 8888
  testing:
    relative-dir: pdf/