storage:
  source:
    directory: ${LOCAL_SOURCE_DIR}/
    extension: ${FILE_EXT:.pdf}
  type: ${STORAGE_TYPE:LOCAL}
  gs:
    project: ${GCP_PPROJECT:algus-project-382}
    bucket: ${GCP_EL_BUCKET:algus-bucket}

quarkus:
  log:
    category:
      "org.example":
        level: INFO
  package:
    type: uber-jar

"%dev":
  quarkus:
    http:
      port: 8181
    log:
      category:
        "org.example":
          level: DEBUG

"%test":
  quarkus:
    http:
      test-port: 8888
  testing:
    relative-dir: pdf/