/*
 * This file is generated by jOOQ.
 */
package org.example.dao.jooq.model;


import java.util.Arrays;
import java.util.List;

import org.example.dao.jooq.model.tables.Podcast;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElService extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>el_service</code>
     */
    public static final ElService EL_SERVICE = new ElService();

    /**
     * The table <code>el_service.podcast</code>.
     */
    public final Podcast PODCAST = Podcast.PODCAST;

    /**
     * No further instances allowed
     */
    private ElService() {
        super("el_service", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Podcast.PODCAST
        );
    }
}
