/*
 * This file is generated by jOOQ.
 */
package org.example.dao.jooq.model;


import org.example.dao.jooq.model.tables.Podcast;
import org.example.dao.jooq.model.tables.records.PodcastRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * el_service.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PodcastRecord> PODCAST_PKEY = Internal.createUniqueKey(Podcast.PODCAST, DSL.name("podcast_pkey"), new TableField[] { Podcast.PODCAST.ID }, true);
}
