/*
 * This file is generated by jOOQ.
 */
package org.example.dao.jooq.model;


import org.example.dao.jooq.model.tables.Podcast;


/**
 * Convenience access to all tables in el_service.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>el_service.podcast</code>.
     */
    public static final Podcast PODCAST = Podcast.PODCAST;
}
